name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks"

[commands]
dev = "npx prisma generate && npx prisma migrate deploy && npm exec remix vite:dev"
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_customers,read_orders"


